inputs:
  working-directory:
    required: false
    default: '.'
runs:
  using: composite
  steps:
    -
      name: Run `npm ci` with retries
      shell: bash
      run: npm run install-deps -- --ci --root-directory "${{ inputs.working-directory }}"
