name: checks.external-urls

on:
  schedule:
    - cron: '0 0 * * 0' # at 00:00 on every Sunday

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup node
        uses: ./.github/actions/setup-node
      -
        name: Install dependencies
        uses: ./.github/actions/npm-install-dependencies
      -
        name: Test
        run: npm run check:external-urls
