name: quality-checks

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-command:
          - npm run lint:eslint
          - npm run lint:yaml
          - npm run lint:md
          - npm run lint:md:relative-urls
          - npm run lint:md:consistency
        os: [ macos, ubuntu, windows ]
      fail-fast: false # Still interested to see results from other combinations
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: ./.github/actions/setup-node
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: ${{ matrix.lint-command }}
