name: e2e-tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
      fail-fast: false # So it still runs on other OSes if one of them fails
    runs-on: ${{ matrix.os }}-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup node
        uses: ./.github/actions/setup-node
      -
        name: Install dependencies
        run: npm ci
      -
        name: Run e2e tests
        run: npm run test:cy:run
